/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'webyog' at '11/8/15 12:34 PM' with Gradle 2.2.1
 *
 * @author webyog, @date 11/8/15 12:34 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
