/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'webyog' at '11/8/15 12:34 PM' with Gradle 2.2.1
 *
 * @author webyog, @date 11/8/15 12:34 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
